project: alert_system
experiment_name: training_alert
savepath:

experiment:
  filename_img:
  filename_labels:
  test_filename_img:
  test_filename_labels:
  batch_size: 12
  num_epochs: 100
  lr: 0.001   
  initialization: 'normal'
