project: alert_system
experiment_name: training_alert
savepath:

experiment:
  filename_img: testing_alert/images.txt
  filename_labels: testing_alert/labels.txt
  test_filename_img: testing_alert/images.txt
  test_filename_labels: testing_alert/labels.txt
  batch_size: 4
  num_epochs: 100
  lr: 0.001   
  initialization: 'normal'
  random_seed: 10
  step: 10
  id: 0
  device_name: 'cuda:1'
